### ISSUE TITLE
Permissions auth.users.view

### ISSUE THREAD

**Issue by gdugas** [jelix/jcommunity-module#3]
Si je suis connecté en tant qu'un utilisateur lambda qui n'a pas la permission "**auth.users.view**: _View informations about a user_", je peux tout de même voir le profil de l'utilisateur admin ou autre via /jcommunity/account/show?user=admin

**Comment by laurentj** [comment]
Finalement j'ai changé d'avis, vu que jcommunity est de plus en plus utilisé pour accéder à des app privées. La page des profiles tient compte maintenant de la permission `auth.users.view`. commit e8e13cdb29e8291cebd3013dcb3b66d3bf789492.

Il n'est jamais trop tard pour bien faire :-)
